-- Migration 009: Client code (TPS-CLI-0001) + client-level document attachments
--
-- Adds:
--   1. clients.client_code  — human-readable, unique, never-reused id (TPS-CLI-0001),
--      generated by a BEFORE INSERT trigger so it works for ANY insert path
--      (app form OR Google Sheets sync).
--   2. fn_can_edit_clients() — SQL mirror of the app's edit-rights check
--      (super_admin OR profiles.can_edit_clients).
--   3. client_documents table — GST / PAN / FSSAI / Other files per client.
--   4. Storage RLS policies on the (previously policy-less) `documents` bucket:
--      every staff member can VIEW; only client-editors can upload/replace/remove
--      client docs. Project docs keep manager+/executive upload rights.

-- ── 1. CLIENT CODE ───────────────────────────────────────────────────────────
create sequence if not exists client_code_seq start 1;

alter table clients add column if not exists client_code text unique;

create or replace function fn_set_client_code()
returns trigger
language plpgsql
as $$
begin
  if new.client_code is null then
    new.client_code := 'TPS-CLI-' || lpad(nextval('client_code_seq')::text, 4, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_client_code on clients;
create trigger trg_set_client_code
  before insert on clients
  for each row execute function fn_set_client_code();

-- ── 2. EDIT-RIGHTS HELPER ────────────────────────────────────────────────────
create or replace function fn_can_edit_clients()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select role = 'super_admin' or can_edit_clients
     from profiles where id = auth.uid()),
    false
  );
$$;

-- ── 3. CLIENT DOCUMENTS ──────────────────────────────────────────────────────
do $$ begin
  create type client_document_category as enum ('gst', 'pan', 'fssai', 'other');
exception when duplicate_object then null;
end $$;

create table if not exists client_documents (
  id              uuid primary key default uuid_generate_v4(),
  client_id       uuid not null references clients(id) on delete cascade,
  category        client_document_category not null,
  file_name       text not null,
  storage_path    text not null,
  file_size_bytes bigint,
  mime_type       text,
  uploaded_by     uuid references profiles(id),
  created_at      timestamptz not null default now()
);
create index if not exists client_documents_client_idx on client_documents(client_id);

alter table client_documents enable row level security;

drop policy if exists "client_documents_select" on client_documents;
create policy "client_documents_select" on client_documents
  for select using (
    has_role('super_admin','director','manager','executive','accounts','auditor')
  );

drop policy if exists "client_documents_insert" on client_documents;
create policy "client_documents_insert" on client_documents
  for insert with check (fn_can_edit_clients());

drop policy if exists "client_documents_delete" on client_documents;
create policy "client_documents_delete" on client_documents
  for delete using (fn_can_edit_clients());

-- ── 4. STORAGE RLS (documents bucket) ────────────────────────────────────────
-- Bucket is private; without policies nobody (except service_role) could read or
-- write. Path convention: client docs -> 'clients/<client_id>/<file>',
--                          project docs -> '<project_id>/<file>'.

drop policy if exists "documents_read_staff" on storage.objects;
create policy "documents_read_staff" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'documents'
    and has_role('super_admin','director','manager','executive','accounts','auditor')
  );

drop policy if exists "documents_upload" on storage.objects;
create policy "documents_upload" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'documents'
    and (
      ((storage.foldername(name))[1] = 'clients' and fn_can_edit_clients())
      or ((storage.foldername(name))[1] <> 'clients'
          and has_role('super_admin','director','manager','executive'))
    )
  );

drop policy if exists "documents_delete" on storage.objects;
create policy "documents_delete" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'documents'
    and (
      ((storage.foldername(name))[1] = 'clients' and fn_can_edit_clients())
      or ((storage.foldername(name))[1] <> 'clients'
          and has_role('super_admin','director','manager','executive'))
    )
  );
